---
output:
  pdf_document: default
  html_document: default
---
```{r}
#1a
data <- data.frame(
  Respondents = 1:20,
  Sex = c(2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2),
  Fathers_Occupation = c(1, 3, 3, 1, 1, 2, 3, 1, 1, 2, 1, 3, 2, 3, 3, 1, 1, 1, 2, 1),
  Persons_at_Home = c(5, 7, 3, 8, 5, 9, 6, 8, 8, 4, 7, 7, 6, 7, 8, 8, 1, 11, 7, 6),
  Siblings_at_School = c(6, 4, 4, 1, 2, 3, 5, 1, 1, 2, 3, 2, 1, 5, 2, 1, 5, 5, 3, 2),
  Types_of_Houses = c(1, 2, 3, 1, 1, 3, 3, 2, 2, 3, 2, 3, 3, 2, 3, 2, 1, 3, 3, 2)
)

# 1b
str(data)
summary(data)

```
```{r}
#1c
mean_siblings <- mean(data$Siblings_at_School)
mean_siblings

is_mean_five <- mean_siblings == 5
is_mean_five
```
```{r}
#1d
first_two_rows <- data[1:2, ]
print(first_two_rows)

```
```{r}
# Extract the 3rd and 5th rows with the 2nd and 4th columns
subset_rows <- data[c(3, 5), c(2, 4)]
print(subset_rows)

```
```{r}
# Select the unique types of houses
types_houses <- unique(data$Types_of_Houses)
print(types_houses)
```
```{r}
# Select Male respondents with Father's occupation as Farmer
male_farmers <- data[data$Sex == 1 & data$Fathers_Occupation == 1, ]
print(male_farmers)

```
```{r}
# Select Female respondents with 5 or more siblings attending school
female_siblings <- data[data$Sex == 2 & data$Siblings_at_School >= 5, ]
print(female_siblings)

```
```{r}
#2
# Create an empty data frame with specified column types
df <- data.frame(
  Ints = integer(),
  Doubles = double(),
  Characters = character(),
  Logicals = logical(),
  Factors = factor(),
  stringsAsFactors = FALSE
)

# Print the structure of the empty data frame
print("Structure of the empty dataframe:")
print(str(df))

```
```{r echo=TRUE, warning=TRUE}
#3a
write.csv(Householdfiles, "Householdfiles.csv", row.names = TRUE)
library(readr)
Householdfiles <- read.csv("Householdfiles.csv")
Householdfiles

```
```{r}
#3b
Householdfiles$Sex <- factor(Householdfiles$Sex, levels = c("m", "f"), labels = c(1,2))
Householdfiles$Sex
```
```{r}
#3c
Householdfiles$Types.of.Houses <- factor(Householdfiles$Types.of.Houses, levels = c("wood", "concrete", "semi-concrete"), labels = c(1, 2, 3))
Householdfiles$Types.of.Houses
```
```{r}
#3d
Householdfiles$Father.s.Occupation <- factor(Householdfiles$Father.s.Occupation, levels = c(1, 2, 3), labels = c("Farmer", "Driver", "Others"))
Householdfiles$Father.s.Occupation

```
```{r}
#3e
female_driver <- subset(Householdfiles, Sex == 2 & Father.s.Occupation == "Driver")
female_driver
```
```{r}
#3f
siblings_5_or_more <- subset(Householdfiles, Siblings.at.School >= 5)
siblings_5_or_more
```
```{r}
#4
#The graph illustrates the sentiments expressed in tweets: negative sentiments are represented in red, neutral in orange, and positive in blue. On certain days, such as July 15 and 21, there were a significant number of negative tweets, while other days showed a prevalence of positive or neutral sentiments. This indicates that people’s opinions were varied and shifted in response to events occurring that week, reflecting their tweets.
```
```

