---
output:
  pdf_document: default
  html_document: default
---
```{r}
shoe_size <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5)
height <- c(66.0, 68.0, 64.5, 65.0, 70.0,  64.0, 70.0, 71.0, 72.0, 64.0, 74.0, 67.0, 71.0, 71.0)
gender <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M")

df <- data.frame(ShoeSize = shoe_size, Height = height, Gender = gender)
```

```{r}
#b
males <- subset(df, Gender == "M")
females <- subset(df, Gender == "F")
print(males)
print(females)

#c
mean_shoe_size <- mean(df$ShoeSize)
mean_height <- mean(df$Height)
cat("Mean Shoe Size", mean_shoe_size, "\n")
cat("Mean shoe Size", mean_height, "\n")

#d
correlation <- cor(df$ShoeSize, df$Height)
cat("Correlation  between Shoe Size and Height", correlation, "\n")
```
```{r}
#2
months_vector <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "juanuary", "November", "November", "February", "May", "August", "July", "December", "August", "September", "November", "February", "April")
factor_months_vector <- factor(months_vector)
print(factor_months_vector)
```
```{r}
#3
summary(months_vector)
summary(factor_months_vector)
```
```{r}
#4
direction  <- c("East", "West", "North")
frequency <- c(1, 4, 3)

new_order_data <- factor(direction, levels = c("East", "West", "North"))

print(new_order_data)
```
```{r}
#5
write.csv("import_march.csv", row.names = FALSE)
data <- read.table("import_march.csv", header = TRUE, sep = ",")
data()
```
```{r}
#6
exhaustive_search  <-  function() {
  user_input <- as.integer(readline(prompt = "Choose a number from 1 to 50: "))
  if (user_input < 1 || user_input > 50) {
    return("The number selected is beyond the range of 1 to 50")
  } else if (user_input == 20) {
    return("TRUE")
  } else {
    print(user_input)
  }
}
exhaustive_search()
```
```{r}
#7
calculate_min_bills <- function(price) {
  denominations <- c(1000, 500, 200, 100, 50)
  
  if (price %% 50 != 0) {
    stop("Price must be a number divisible by 50.")
  }
  
  bill_count <- 0
  
  for (denom in denominations) {
    if (price >= denom) {
      count <- price %/% denom
      bill_count <- bill_count + count
      price <- price - (count * denom)
    }
  }
  
  return(bill_count)
}

repeat {
  changeprice_input <- as.numeric(readline(prompt = "Enter the price of the snack (divisible by 50): "))
  
  if (!is.na(changeprice_input) && changeprice_input > 0) {
    break
  } else {
    cat("Please enter a valid positive number divisible by 50.\n")
  }
}

min_bills <- calculate_min_bills(changeprice_input)
cat("Minimum number of bills needed: ", min_bills, "\n")

```
```{r}
grades <- data.frame(
  Name = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80,100),
  Grade4 = c(100, 90, 85, 90)
)
grades
```
```{r}
for (i in 1:nrow(grades)) {
  total <- sum(grades[i, 2:5])
  avg <- total / 4
  if (avg > 90) {
    cat(grades$Name[i], "'s average this semestern is", avg, "/n", sep = "")
  }
}
```
```{r}
for (j in 2:5) {
  avg <- mean(grades[, j])
  if (avg <  80) {
    cat("The", j - 1, "th test was difficult.\n")
  }
}
```
```{r}
for (i in 1:nrow(grades)) {
  highest <- grades[i, 2]
  for (j in 3:5) {
    if (grades[i, j] > highest) {
      highest <- grades[i, j]
    }
  }
  if (highest > 90) {
    cat(grades$Name[i], "'s highest grade tthis semester is ", highest, "\n", sep = "")
  }
}
```

